### PR TITLE
product routes and controllers

### PR DESCRIPTION
**Pull request by maestro-1**
#### Handles Products endpoint for API

####Handles the getting, adding, deleting and updating of products from/in the database. 

#### How should this manually be Tested?
- `git clone` __https://github.com/devcareer/Dae-Alright-Backend__
- `cd` **Dae-Alright-Backend**
- `git checkout <branch-name>`
- `npm install`
- `npm test`

### CODE REVIEW

**Review by meetKazuki — CHANGES_REQUESTED** [review]
* Rebase! Rebase!! Rebase!!!
* Your change is breaking our build on TravisCI. Fix ASAP

**Comment by supercede** [comment]
The build fails, some of the tests are failing pertaining to the user and vendors sign up. Did you change anything?

**Comment by supercede** [comment]
Do run lint -- --fix too

**Comment by TundeMercy** [comment]
@maestro-1 All your local 14 commits are still in there, find a way to squash them. You can follow the step I suggested

**Comment by meetKazuki** [comment]
It's passing now @maestro-1. Rebase so that we can merge

**Pull request merged**
