### PR TITLE
fix user and vendor name validation

### PR DESCRIPTION
**Pull request by supercede**
#### What does this PR do?
Allows space in user and vector name-field during signup

#### How should this manually be Tested?
- `git clone` __https://github.com/devcareer/Dae-Alright-Backend__
- `cd` **Dae-Alright-Backend**
- `git checkout <branch-name>`
- `npm install`
- `npm test`

#### What are the relevant ~~Pivotal Tracker~~ **Trello** stories?
fix user and vendor validation schema

### CODE REVIEW

**Comment by supercede** [comment]
[fix user and vendor validation schema](https://trello.com/c/1wvWnNxd/15-fix-user-and-vendor-validation-schema)

**Review by meetKazuki — APPROVED** [review]

**Comment by meetKazuki** [comment]
Is this still needed @supercede?
If yes, please rebase so that I can merge

**Review by maestro-1 — APPROVED** [review]
I think you're good to go

**Comment by meetKazuki** [comment]
Just rebase @supercede, so that we can merge

**Review by TundeMercy — COMMENTED** [review]
@supercede Please rebase so we can merge

**Comment by supercede** [comment]
> @supercede Please rebase so we can merge

Done

**Comment by supercede** [comment]
> Just rebase @supercede, so that we can merge

Done Tunde

**Pull request merged**
